/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

// Models
import models.Patient;
import models.Schedule;
import models.HealthPlan;
import models.Consultation;

// Utils
import java.awt.Component;
import java.util.ArrayList;

// Views
import views.patient.PatientsTable;
import views.health_plan.HealthPlansTable;
import views.consultation.ConsultationsTable;

// Controllers
import controllers.PatientsController;
import controllers.SchedulesController;
import controllers.HealthPlansController;
import controllers.ConsultationsController;

/**
 *
 * @author João Salomão
 */

public class MainFrame extends javax.swing.JFrame {

    ArrayList<Patient> patients;
    ArrayList<Schedule> schedules;
    ArrayList<HealthPlan> healthPlans;
    ArrayList<Consultation> consultations;
    
    PatientsController patientsController;
    SchedulesController schedulesController;
    HealthPlansController healthPlansController;
    ConsultationsController consultationsController;
    
    Component patientsListComponent;
    Component healthPlansListComponent;
    Component consultationsListComponent;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        
        
        patientsController = new PatientsController();
        schedulesController = new SchedulesController();
        healthPlansController = new HealthPlansController();
        consultationsController = new ConsultationsController();
        
        patients = patientsController.all();
        schedules = schedulesController.all();
        healthPlans = healthPlansController.all();
        consultations = consultationsController.all();

        patientsListComponent = tabbedPane.add(new PatientsTable(patients, healthPlans, schedules,patientsController));
        consultationsListComponent = tabbedPane.add(new ConsultationsTable(consultations, consultationsController));
        healthPlansListComponent = tabbedPane.add(new HealthPlansTable(healthPlans, healthPlansController));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("App Pediatra");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 435));

        tabbedPane.setPreferredSize(new java.awt.Dimension(900, 435));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
