/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.health_plan;

import javax.swing.JOptionPane;
import models.HealthPlan;

/**
 *
 * @author João Salomão
 */
public class Form extends javax.swing.JFrame {

    private final HealthPlansTable healthPlansTable;
    private HealthPlan healthPlan;
    private boolean isEdit;

    /**
     * Creates new form Form
     *
     * @param healthPlansTable
     * @param isEdit
     */
    public Form(HealthPlansTable healthPlansTable, boolean isEdit) {
        initComponents();
        setLocationRelativeTo(null);
        
        this.healthPlansTable = healthPlansTable;
        this.isEdit = isEdit;
        
        if (isEdit) {
            healthPlan = healthPlansTable.getSelectedHealthPlan();
            nameTextField.setText(healthPlan.getName());
            lcmTextField.setText(Integer.toString(healthPlan.getAppointmentLimit()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameTextField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        lcmTextField = new javax.swing.JTextField();
        lcmLabel = new javax.swing.JLabel();
        leftButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nameTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        nameLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nameLabel.setText("Nome");

        lcmTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lcmLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lcmLabel.setText("LCM");

        leftButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        leftButton.setText("Sair");
        leftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftButtonActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        saveButton.setText("Salvar");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addGap(0, 268, Short.MAX_VALUE))
                            .addComponent(nameTextField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lcmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lcmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(leftButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(lcmLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lcmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftButton)
                    .addComponent(saveButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftButtonActionPerformed
        dispose();
    }//GEN-LAST:event_leftButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String name = nameTextField.getText();
        int lcm = Integer.parseInt(lcmTextField.getText());
        boolean result;
        
        if (isEdit) {
            healthPlan.setName(name);
            healthPlan.setAppointmentLimit(lcm);
            
            result = healthPlansTable.updateRow(healthPlan);
            if (result) {
                JOptionPane.showMessageDialog(this, "O Plano de saúde foi atualizado com sucesso.");
            } else {
                JOptionPane.showMessageDialog(this, "Algo deu errado, tente novamente.");
            }
        } else {
            healthPlan = new HealthPlan(name, lcm);
            result = healthPlansTable.addRow(healthPlan);
            
            if (result) {
                JOptionPane.showMessageDialog(this, "O Plano de saúde foi criado com sucesso.");
                isEdit = true;
            } else {
                JOptionPane.showMessageDialog(this, "Algo deu errado, tente novamente.");
            }
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lcmLabel;
    private javax.swing.JTextField lcmTextField;
    private javax.swing.JButton leftButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
